### ISSUE TITLE
Ionic 6 LaunchNavigator Plugin problem

### ISSUE THREAD

**Issue by mahmoudsaghir** [dpa99c/phonegap-launch-navigator-example#13]
I followed the steps for the LaunchNavigator plugin in this link https://ionicframework.com/docs/native/launch-navigator/   step by step.
But i faced this problem at launchNavigator.navigate

TypeError: Object(...) is not a function
    at LaunchNavigator.navigate

I am using the following plugin :
"@ionic-native/launch-navigator": "^5.26.0"
And i am using cordova 9.0.0 (cordova-lib@9.0.1).

**Comment by dpa99c** [comment]
This relates to the [Ionic Typescript wrapper for this plugin](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/launch-navigator/index.ts) which is owned/maintained by [Ionic](https://github.com/ionic-team) and is not part of this plugin.
Please raise an issue against [Ionic Native](https://github.com/ionic-team/ionic-native/) instead.
