### ISSUE TITLE
Exception: can't find variable: launchnavigator 

### ISSUE THREAD

**Issue by dregop** [dpa99c/phonegap-launch-navigator-example#5]
Hello,
I recently download the IonicExample to test it on my phone using IonicView. 
I have the same issue on ios or android : 
When i click on the button "Navigate" this error message is poping : "Exception: can't find variable: launchnavigator" 

What should i do ?
Thanks.

**Comment by dpa99c** [comment]
IonicView is a wrapper for simple HTML5 apps. As such, there are only a limited number of [supported plugins](http://docs.ionic.io/tools/view/#supported-plugins), which as you'll see doesn't include this one.

If you want to use this plugin, you need to the [build project as instructed](https://github.com/dpa99c/phonegap-launch-navigator-example#building-and-running) to generate a native app - it won't work with IonicView.

**Comment by dregop** [comment]
Thank you for the quick answer.
