### ISSUE TITLE
ionic3

### ISSUE THREAD

**Issue by bricox** [dpa99c/phonegap-launch-navigator-example#7]
Ionic 3 changed the api for importing the module.  The syntax 

import { LaunchNavigator, LaunchNavigatorOptions } from 'ionic-native'; 

no longer works.  It's my understanding that the syntax would something like

import { LaunchNavigator, LaunchNavigatorOptions } from '@ionic-native/LaunchNavigator';

but I have yet to figure this out.  Is Ionic 3 support planned?  Or can you provide the correct syntax to import the plugin?

**Comment by bricox** [comment]
Well, I think I just figured it out.  

The syntax is:
import { LaunchNavigator, LaunchNavigatorOptions } from '@ionic-native/launch-navigator'; 

I was able to piece this together from 
https://ionicframework.com/docs/native/launch-navigator/

Thanks.

**Comment by dpa99c** [comment]
Added [Ionic3Example](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/Ionic3Example)
